#ifndef TOKEN_H
#define TOKEN_H

#include <string>

enum TokenType {
    TOK_EOF, TOK_PROGRAM, TOK_END, TOK_INTEGER, TOK_REAL, TOK_LOGICAL,
    TOK_IF, TOK_THEN, TOK_ELSE, TOK_ENDIF, TOK_DO, TOK_WHILE, TOK_ENDDO,
    TOK_PRINT, TOK_READ, TOK_IDENTIFIER, TOK_NUMBER, TOK_STRING,
    TOK_ASSIGN, TOK_PLUS, TOK_MINUS, TOK_MULTIPLY, TOK_DIVIDE,
    TOK_LPAREN, TOK_RPAREN, TOK_COMMA, TOK_NEWLINE,
    TOK_EQ, TOK_NE, TOK_LT, TOK_LE, TOK_GT, TOK_GE,
    TOK_AND, TOK_OR, TOK_NOT, TOK_TRUE, TOK_FALSE,
    TOK_PINMODE, TOK_DIGITALWRITE, TOK_DIGITALREAD, TOK_DELAY,
    TOK_INPUT, TOK_OUTPUT, TOK_HIGH, TOK_LOW, TOK_CALL
};

struct Token {
    TokenType type;
    std::string value;
    int line;
};

#endif // TOKEN_H
